version: "3.7"
services:
  gatsby:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ./app:/home/node
    environment:
      - NODE_ENV=development
    stdin_open: true
