version: "3.7"
services:
  gatsby:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
      - "9000:9000"
    volumes:
      - ./app:/home/node
    environment:
      - NODE_ENV=development
    stdin_open: true
    command:
      sh -c 'npm install && npm run develop'
